### ISSUE TITLE
更新, 通知on で確認アラート

### ISSUE THREAD

**Issue by elzup** [footopic/web-prototype#237]
もらった意見: 投稿時は通知on でいいが, 更新時はdefault で off になっていて欲しい
- 更新で通知on の場合は投稿ボタンで確認ダイアログを出す
- または投稿時のオプションが on, off どちらであれ最初は通知off として登録する
- または通知カラムを廃止して, 新規はon 更新はoff をデフォルトにする

**Comment by akameco** [comment]
Close #238
